name: Ops Challenge

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        id: publish-docker-image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: figmentnetworks/ops-challenge-skeleton
          tags: latest
